#!/usr/bin/env python3
"""Build lib/Sound/SfxData.h: the procedural siren SFX bank for the I2S DAC.

All entries are synthesised here with numpy (FM-swept tones), so the bank is
fully reproducible with no network or licensing. Each is converted to the
firmware's I2S format (16 kHz mono 16-bit PCM), peak-normalised to full scale
and faded. Playback VOLUME is applied at runtime in Sound.cpp, not baked in.

The first three sirens are the auditioned-and-approved set; the last three are
permutations around them (a descending counterpart, a faster wail, a slower
two-tone) to give six distinct options for assigning to teams + death later.
"""
import os
import sys

import numpy as np

RATE = 16000
FADE_MS = 40
OUT_HEADER = os.path.join(os.path.dirname(__file__), "..", "lib", "Sound", "SfxData.h")

# (ident, seconds, freq-fn(t) -> instantaneous frequency in Hz).
SIRENS = [
    # --- approved set (unchanged) ---
    ("siren-wail",      0.9, lambda t: 850.0 + 350.0 * np.sin(2 * np.pi * 3.0 * t)),
    ("siren-warble",    0.8, lambda t: np.where((t * 8.0) % 1.0 < 0.5, 740.0, 1040.0)),
    ("siren-rise",      0.7, lambda t: 400.0 + (1600.0 - 400.0) * (t / 0.7)),
    # --- permutations around the approved set ---
    ("siren-fall",      0.7, lambda t: 1600.0 - (1600.0 - 400.0) * (t / 0.7)),
    ("siren-wail-fast", 0.9, lambda t: 850.0 + 350.0 * np.sin(2 * np.pi * 6.0 * t)),
    ("siren-twotone",   0.8, lambda t: np.where((t * 4.0) % 1.0 < 0.5, 600.0, 900.0)),
]


def synth_death():
    """Death cue: three short rise/fall "woo" pulses then a long descending
    "wiooooo" whose pitch and amplitude both tail to near-zero (~2.3 s total)."""
    segs = []
    for _ in range(3):                                   # woo - woo - woo
        t = np.arange(int(0.25 * RATE)) / RATE
        f = 500.0 + 300.0 * np.sin(np.pi * t / 0.25)     # 500 -> 800 -> 500 bend
        bell = np.sin(np.pi * t / 0.25)                  # 0..1..0 amplitude
        segs.append(np.sin(2 * np.pi * np.cumsum(f) / RATE) * bell)
        segs.append(np.zeros(int(0.07 * RATE)))          # gap between pulses
    dur = 1.3                                            # wiooooo: long descent
    t = np.arange(int(dur * RATE)) / RATE
    f = 150.0 + 750.0 * (1.0 - t / dur)                  # 900 -> 150 Hz glide
    tail = np.sin(2 * np.pi * np.cumsum(f) / RATE) + 0.2 * np.sin(4 * np.pi * np.cumsum(f) / RATE)
    env = (1.0 - t / dur) ** 1.5                         # amplitude tails to zero
    a = int(0.02 * RATE)
    env[:a] *= np.linspace(0.0, 1.0, a)                  # tiny attack, no click
    segs.append(tail * env)
    x = np.concatenate(segs).astype(np.float32)
    return np.clip(x / np.max(np.abs(x)) * 32767.0, -32768, 32767).astype(np.int16)


def synth_siren(seconds, freq_fn):
    t = np.arange(int(seconds * RATE)) / RATE
    f = np.asarray(freq_fn(t), dtype=np.float32)
    phase = 2 * np.pi * np.cumsum(f) / RATE              # FM via phase accumulation
    wave = np.sin(phase) + 0.25 * np.sin(2 * phase)      # 2nd harmonic for synthy edge
    env = np.ones_like(wave)
    a = int(0.02 * RATE)                                  # 20 ms attack to avoid a click
    env[:a] = np.linspace(0.0, 1.0, a)
    x = wave * env
    peak = np.max(np.abs(x))
    x = x / peak                                          # full-scale normalise
    fade = int(FADE_MS * RATE / 1000)
    x[-fade:] *= np.linspace(1.0, 0.0, fade)              # fade-out tail
    return np.clip(x * 32767.0, -32768, 32767).astype(np.int16)


def main():
    entries = [(ident, synth_siren(secs, fn)) for ident, secs, fn in SIRENS]
    entries.append(("death-woowoo", synth_death()))
    for ident, pcm in entries:
        print(f"  OK  {ident:18s} {len(pcm)/RATE:.2f}s  {len(pcm) * 2 / 1024:.1f} KB")

    lines = [
        "// GENERATED by tools/gen_sfx.py - do not edit by hand.",
        "// Procedural siren bank. Format: 16000 Hz mono 16-bit PCM, peak-normalised",
        "// to full scale (playback volume applied at runtime in Sound.cpp).",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct SfxSample { const char *name; const int16_t *data; size_t len; };",
        "",
    ]
    total = 0
    for ident, pcm in entries:
        arr = "kSfx_" + ident.replace("-", "_")
        total += len(pcm) * 2
        lines.append(f"static const int16_t {arr}[] = {{{','.join(str(int(v)) for v in pcm)}}};")
        lines.append("")
    lines.append("static const SfxSample kSfxBank[] = {")
    for ident, pcm in entries:
        arr = "kSfx_" + ident.replace("-", "_")
        lines.append(f'    {{"{ident}", {arr}, {len(pcm)}}},')
    lines.append("};")
    lines.append(f"static const size_t kSfxBankCount = {len(entries)};")
    lines.append("")

    with open(OUT_HEADER, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\nWrote {os.path.normpath(OUT_HEADER)}: {len(entries)} sirens, "
          f"{total / 1024:.1f} KB total in flash.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
